# Generated by Django 5.2.6 on 2025-11-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
